// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFsyBbRU88IF5N78spCADyXG1kNZ2uXNc',
    appId: '1:935892363904:web:5c45eefccf5e02f0395465',
    messagingSenderId: '935892363904',
    projectId: 'flutter-appa-dev',
    authDomain: 'flutter-appa-dev.firebaseapp.com',
    storageBucket: 'flutter-appa-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRbtm-lZsO0WwLy0bilpSa4UQL_XGanFw',
    appId: '1:935892363904:android:694ebecdd4280d02395465',
    messagingSenderId: '935892363904',
    projectId: 'flutter-appa-dev',
    storageBucket: 'flutter-appa-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO9EI9LLaB8xIjdJGGAnsQQRs5M3MJ9aI',
    appId: '1:935892363904:ios:9e2192bfd9603549395465',
    messagingSenderId: '935892363904',
    projectId: 'flutter-appa-dev',
    storageBucket: 'flutter-appa-dev.appspot.com',
    iosClientId:
        '935892363904-stsbpo066nfqf8pdhm3l2kalnhkqk8mv.apps.googleusercontent.com',
    iosBundleId: 'com.harnicode.gbefun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO9EI9LLaB8xIjdJGGAnsQQRs5M3MJ9aI',
    appId: '1:935892363904:ios:9e2192bfd9603549395465',
    messagingSenderId: '935892363904',
    projectId: 'flutter-appa-dev',
    storageBucket: 'flutter-appa-dev.appspot.com',
    iosClientId:
        '935892363904-stsbpo066nfqf8pdhm3l2kalnhkqk8mv.apps.googleusercontent.com',
    iosBundleId: 'com.harnicode.gbefun',
  );
}
